USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/zte/mooncake/BoardConfigVendor.mk

TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := unknown
TARGET_CPU_ABI := armeabi
TARGET_BOOTLOADER_BOARD_NAME := mooncake

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x02A00000
BOARD_PAGE_SIZE := 0x00000800
BOARD_LDPI_RECOVERY : = true

BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00480000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00480000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x09600000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x127e0000
BOARD_FLASH_BLOCK_SIZE := 0x00020000

TARGET_PREBUILT_KERNEL := device/zte/mooncake/kernel

BOARD_DATA_DEVICE := /dev/block/mtdblock5
BOARD_DATA_FILESYSTEM := auto
BOARD_DATA_FILESYSTEM_OPTIONS := rw
BOARD_SYSTEM_DEVICE := /dev/block/mtdblock4
BOARD_SYSTEM_FILESYSTEM := auto
BOARD_SYSTEM_FILESYSTEM_OPTIONS := rw
BOARD_CACHE_DEVICE := /dev/block/mtdblock3
BOARD_CACHE_FILESYSTEM := auto
BOARD_CACHE_FILESYSTEM_OPTIONS := rw

#BOARD_CUSTOM_RECOVERY_KEYMAPPING := ../../device/zte/mooncake/recovery/recovery_ui.c

